USE [master]
GO

/****** Object:  User [FoodieAppUser]    Script Date: 3/6/2023 3:00:49 PM ******/
DROP USER if exists [FoodieAppUser]
GO

/****** Object:  Login [FoodieAppUser]    Script Date: 3/6/2023 3:00:49 PM ******/
DROP LOGIN [FoodieAppUser]
GO

/****** Object:  Database [XAMFoodies]    Script Date: 3/6/2023 3:00:49 PM ******/
DROP DATABASE [XAMFoodies]
GO

/****** Object:  Database [XAMFoodies]    Script Date: 3/6/2023 3:00:49 PM ******/
CREATE DATABASE [XAMFoodies]
 CONTAINMENT = NONE
GO
ALTER DATABASE [XAMFoodies] SET COMPATIBILITY_LEVEL = 160
GO

ALTER DATABASE [XAMFoodies] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [XAMFoodies] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [XAMFoodies] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [XAMFoodies] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [XAMFoodies] SET ARITHABORT OFF 
GO
ALTER DATABASE [XAMFoodies] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [XAMFoodies] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [XAMFoodies] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [XAMFoodies] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [XAMFoodies] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [XAMFoodies] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [XAMFoodies] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [XAMFoodies] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [XAMFoodies] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [XAMFoodies] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [XAMFoodies] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [XAMFoodies] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [XAMFoodies] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [XAMFoodies] SET DB_CHAINING OFF 
GO
ALTER DATABASE [XAMFoodies] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'XAMFoodies', N'ON'
GO
ALTER DATABASE [XAMFoodies] SET QUERY_STORE = ON
GO
ALTER DATABASE [XAMFoodies] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 2000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

/* For security reasons the login is created disabled and with a random password. */
/****** Object:  Login [FoodieAppUser]    Script Date: 3/6/2023 3:00:49 PM ******/
CREATE LOGIN [FoodieAppUser] WITH PASSWORD=N'foodieappuser', DEFAULT_DATABASE=[XAMFoodies], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER LOGIN [FoodieAppUser] DISABLE
GO

USE [XAMFoodies]
GO
/****** Object:  User [FoodieAppUser]    Script Date: 3/6/2023 3:00:49 PM ******/
CREATE USER [FoodieAppUser] FOR LOGIN [FoodieAppUser] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_datareader] ADD MEMBER [FoodieAppUser]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [FoodieAppUser]
GO

